// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.CandlesHistory.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class CandlesHistoryResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the CandlesHistoryResponseModel
        /// class.
        /// </summary>
        public CandlesHistoryResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CandlesHistoryResponseModel
        /// class.
        /// </summary>
        public CandlesHistoryResponseModel(IList<Candle> history = default(IList<Candle>))
        {
            History = history;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        private void CustomInit() => throw new System.NotImplementedException();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "History")]
        public IList<Candle> History { get; set; }

    }
}
