// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.CandlesHistory.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LastTradePriceResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the LastTradePriceResponseModel
        /// class.
        /// </summary>
        public LastTradePriceResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LastTradePriceResponseModel
        /// class.
        /// </summary>
        public LastTradePriceResponseModel(double lastTradePrice)
        {
            LastTradePrice = lastTradePrice;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastTradePrice")]
        public double LastTradePrice { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
