// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.CandlesHistory.Client.Models
{
    using Newtonsoft.Json;
    
    // ReSharper disable once ClassWithVirtualMembersNeverInherited.Global
    public class PersistenceInfo
    {
        /// <summary>
        /// Initializes a new instance of the PersistenceInfo class.
        /// </summary>
        public PersistenceInfo()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PersistenceInfo class.
        /// </summary>
        public PersistenceInfo(long totalCandlesPersistedCount, long totalCandleRowsPersistedCount, int batchesToPersistQueueLength, int candlesToDispatchQueueLength, Times times = default(Times), Throughput throughput = default(Throughput))
        {
            Times = times;
            Throughput = throughput;
            TotalCandlesPersistedCount = totalCandlesPersistedCount;
            TotalCandleRowsPersistedCount = totalCandleRowsPersistedCount;
            BatchesToPersistQueueLength = batchesToPersistQueueLength;
            CandlesToDispatchQueueLength = candlesToDispatchQueueLength;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        private void CustomInit() => throw new System.NotImplementedException();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Times")]
        public Times Times { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Throughput")]
        public Throughput Throughput { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalCandlesPersistedCount")]
        public long TotalCandlesPersistedCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalCandleRowsPersistedCount")]
        public long TotalCandleRowsPersistedCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BatchesToPersistQueueLength")]
        public int BatchesToPersistQueueLength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CandlesToDispatchQueueLength")]
        public int CandlesToDispatchQueueLength { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            Times?.Validate();
            Throughput?.Validate();
        }
    }
}
