// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace Lykke.Service.CandlesHistory.Client.Models
{
    public class Throughput
    {
        /// <summary>
        /// Initializes a new instance of the Throughput class.
        /// </summary>
        public Throughput()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Throughput class.
        /// </summary>
        public Throughput(int averageCandlesPersistedPerSecond, int averageCandleRowsPersistedPerSecond)
        {
            AverageCandlesPersistedPerSecond = averageCandlesPersistedPerSecond;
            AverageCandleRowsPersistedPerSecond = averageCandleRowsPersistedPerSecond;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        private void CustomInit() => throw new System.NotImplementedException();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AverageCandlesPersistedPerSecond")]
        public int AverageCandlesPersistedPerSecond { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AverageCandleRowsPersistedPerSecond")]
        public int AverageCandleRowsPersistedPerSecond { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
