// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.CandlesHistory.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TradingVolumeResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the TradingVolumeResponseModel class.
        /// </summary>
        public TradingVolumeResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TradingVolumeResponseModel class.
        /// </summary>
        public TradingVolumeResponseModel(double volume, double oppositeVolume)
        {
            Volume = volume;
            OppositeVolume = oppositeVolume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OppositeVolume")]
        public double OppositeVolume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
