// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.CandlesHistory.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TradePriceChangeResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the TradePriceChangeResponseModel
        /// class.
        /// </summary>
        public TradePriceChangeResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TradePriceChangeResponseModel
        /// class.
        /// </summary>
        public TradePriceChangeResponseModel(double tradePriceChange)
        {
            TradePriceChange = tradePriceChange;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TradePriceChange")]
        public double TradePriceChange { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
